In [1]:
import pandas as pd
df=pd.read_json('News_Dataset.json',lines=True)

In [2]:
df.head(5)

link  \
0  https://www.huffpost.com/entry/covid-boosters-...   
1  https://www.huffpost.com/entry/american-airlin...   
2  https://www.huffpost.com/entry/funniest-tweets...   
3  https://www.huffpost.com/entry/funniest-parent...   
4  https://www.huffpost.com/entry/amy-cooper-lose...   

                                            headline   category  \
0  Over 4 Million Americans Roll Up Sleeves For O...  U.S. NEWS   
1  American Airlines Flyer Charged, Banned For Li...  U.S. NEWS   
2  23 Of The Funniest Tweets About Cats And Dogs ...     COMEDY   
3  The Funniest Tweets From Parents This Week (Se...  PARENTING   
4  Woman Who Called Cops On Black Bird-Watcher Lo...  U.S. NEWS   

                                   short_description               authors  \
0  Health experts said it is too early to predict...  Carla K. Johnson, AP   
1  He was subdued by passengers and crew when he ...        Mary Papenfuss   
2  "Until you have a dog you don't understand wha...         Elyse Wanshel   
3  "Accidentally put grown-up toothpaste on my to...      Caroline Bologna   
4  Amy Cooper accused investment firm Franklin Te...        Nina Golgowski   

        date  
0 2022-09-23  
1 2022-09-23  
2 2022-09-23  
3 2022-09-23  
4 2022-09-22

In [3]:
df.shape

(209527, 6)

In [4]:
df.columns

Index(['link', 'headline', 'category', 'short_description', 'authors', 'date'], dtype='object')

In [5]:
df.dtypes

link                         object
headline                     object
category                     object
short_description            object
authors                      object
date                 datetime64[ns]
dtype: object

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 209527 entries, 0 to 209526
Data columns (total 6 columns):
 #   Column             Non-Null Count   Dtype         
---  ------             --------------   -----         
 0   link               209527 non-null  object        
 1   headline           209527 non-null  object        
 2   category           209527 non-null  object        
 3   short_description  209527 non-null  object        
 4   authors            209527 non-null  object        
 5   date               209527 non-null  datetime64[ns]
dtypes: datetime64[ns](1), object(5)
memory usage: 9.6+ MB


In [7]:
df.describe()

C:\Users\WONDER\AppData\Local\Temp\ipykernel_7872\3627053830.py:1: FutureWarning: Treating datetime data as categorical rather than numeric in `.describe` is deprecated and will be removed in a future version of pandas. Specify `datetime_is_numeric=True` to silence this warning and adopt the future behavior now.
  df.describe()


link        headline  \
count                                              209527          209527   
unique                                             209486          207996   
top     https://www.huffingtonpost.comhttps://www.wash...  Sunday Roundup   
freq                                                    2              90   
first                                                 NaN             NaN   
last                                                  NaN             NaN   

        category short_description authors                 date  
count     209527            209527  209527               209527  
unique        42            187022   29169                 3890  
top     POLITICS                            2014-03-25 00:00:00  
freq       35602             19712   37418                  100  
first        NaN               NaN     NaN  2012-01-28 00:00:00  
last         NaN               NaN     NaN  2022-09-23 00:00:00

In [8]:
df.duplicated().sum()

13

In [9]:
df=df.drop_duplicates()

In [10]:
df.shape

(209514, 6)

In [26]:
import textdistance
textdistance.hamming(df['headline'][0], df['short_description'][0])

148

In [27]:
for i in range(10):
    print(textdistance.hamming(df['link'][i], df['short_description'][i]))

154
154
94
156
152
157
130
114
145
144


In [28]:
for i in range(10):
    print(textdistance.hamming(df['headline'][i], df['short_description'][i]))

148
154
66
156
150
159
115
115
143
143


In [30]:
for i in range(10):
    print(textdistance.levenshtein.normalized_similarity(df['headline'][i], df['short_description'][i]))

0.20779220779220775
0.23899371069182385
0.17391304347826086
0.16981132075471694
0.1923076923076923
0.2407407407407407
0.2100840336134454
0.25
0.25
0.18918918918918914


In [31]:
for i in range(10):
    print(textdistance.levenshtein.normalized_similarity(df['link'][i], df['short_description'][i]))

0.1428571428571429
0.13207547169811318
0.12121212121212122
0.16981132075471694
0.15384615384615385
0.16666666666666663
0.1127819548872181
0.14655172413793105
0.18243243243243246
0.14864864864864868


In [33]:
for i in range(10):
        print(textdistance.jaro_winkler(df['link'][i], df['short_description'][i]))

0.5062663981209771
0.5914964433011256
0.4680320360467419
0.49733719590505227
0.5392690026605945
0.5333291376905084
0.5244672767892582
0.5068283440697234
0.5487703452492185
0.5483621801601823


In [34]:
for i in range(10):
        print(textdistance.jaro_winkler(df['headline'][i], df['short_description'][i]))

0.55134996582365
0.5993989992293999
0.5744740020340707
0.5088632860722139
0.5657231657231657
0.5664168136390358
0.5647094658759025
0.595579133510168
0.5816263632053106
0.5553303303303303


In [35]:
for i in range(10):
    print(textdistance.jaccard(df['headline'][i], df['short_description'][i]))

0.3372093023255814
0.42528735632183906
0.4
0.25
0.36257309941520466
0.3181818181818182
0.3880597014925373
0.40310077519379844
0.37423312883435583
0.3248407643312102


In [41]:
df['len_of_news']=df['headline']+df['short_description']

In [44]:
df.columns

Index(['link', 'headline', 'category', 'short_description', 'authors', 'date',
       'len_of_news'],
      dtype='object')

In [51]:
df.drop(['authors','link','date','headline','short_description'],inplace=True,axis=1)

In [52]:
df['len_news']=df['len_of_news'].apply(lambda x: len(str(x)))

In [56]:
df.head(5)

category                                        len_of_news  len_news
0  U.S. NEWS  Over 4 Million Americans Roll Up Sleeves For O...       230
1  U.S. NEWS  American Airlines Flyer Charged, Banned For Li...       248
2     COMEDY  23 Of The Funniest Tweets About Cats And Dogs ...       133
3  PARENTING  The Funniest Tweets From Parents This Week (Se...       215
4  U.S. NEWS  Woman Who Called Cops On Black Bird-Watcher Lo...       233

In [146]:
import re
def preprocess_text(text):
    text=re.sub('[^a-zA-Z]', ' ', text)
    text=text.lower()
    words=text.split()
    preprocessed_text = ' '.join(words)
    return preprocessed_text

    

In [147]:
df['len_of_news']=df['len_of_news'].apply(lambda x: preprocess_text(str(x)))

In [148]:
df['category'].value_counts()

POLITICS          35601
WELLNESS          17942
ENTERTAINMENT     17362
TRAVEL             9900
STYLE & BEAUTY     9811
PARENTING          8791
HEALTHY LIVING     6694
QUEER VOICES       6347
FOOD & DRINK       6340
BUSINESS           5992
COMEDY             5400
SPORTS             5077
BLACK VOICES       4583
HOME & LIVING      4320
PARENTS            3955
THE WORLDPOST      3664
WEDDINGS           3653
WOMEN              3571
CRIME              3562
IMPACT             3484
DIVORCE            3426
WORLD NEWS         3299
MEDIA              2944
WEIRD NEWS         2777
GREEN              2622
WORLDPOST          2579
RELIGION           2577
STYLE              2254
SCIENCE            2206
TECH               2100
TASTE              2096
MONEY              1756
ARTS               1509
ENVIRONMENT        1443
FIFTY              1401
GOOD NEWS          1398
U.S. NEWS          1377
ARTS & CULTURE     1339
COLLEGE            1144
LATINO VOICES      1130
CULTURE & ARTS     1074
EDUCATION       

In [149]:
df['category_merge']=df['category'].replace({"HEALTHY LIVING": "WELLNESS",
"QUEER VOICES": "GROUPS VOICES",
"BUSINESS": "BUSINESS & FINANCES",
"PARENTS": "PARENTING",
"BLACK VOICES": "GROUPS VOICES",
"THE WORLDPOST": "WORLD NEWS",
"STYLE": "STYLE & BEAUTY",
"GREEN": "ENVIRONMENT",
"TASTE": "FOOD & DRINK",
"WORLDPOST": "WORLD NEWS",
"SCIENCE": "SCIENCE & TECH",
"TECH": "SCIENCE & TECH",
"MONEY": "BUSINESS & FINANCES",
"ARTS": "ARTS & CULTURE",
"COLLEGE": "EDUCATION",
"LATINO VOICES": "GROUPS VOICES",
"CULTURE & ARTS": "ARTS & CULTURE",
"FIFTY": "MISCELLANEOUS",
"GOOD NEWS": "MISCELLANEOUS"})

In [150]:
df['category_merge'].value_counts()

POLITICS               35601
WELLNESS               24636
ENTERTAINMENT          17362
PARENTING              12746
STYLE & BEAUTY         12065
GROUPS VOICES          12060
TRAVEL                  9900
WORLD NEWS              9542
FOOD & DRINK            8436
BUSINESS & FINANCES     7748
COMEDY                  5400
SPORTS                  5077
HOME & LIVING           4320
SCIENCE & TECH          4306
ENVIRONMENT             4065
ARTS & CULTURE          3922
WEDDINGS                3653
WOMEN                   3571
CRIME                   3562
IMPACT                  3484
DIVORCE                 3426
MEDIA                   2944
MISCELLANEOUS           2799
WEIRD NEWS              2777
RELIGION                2577
EDUCATION               2158
U.S. NEWS               1377
Name: category_merge, dtype: int64

In [151]:
df['category_merge'].unique()

array(['U.S. NEWS', 'COMEDY', 'PARENTING', 'WORLD NEWS', 'ARTS & CULTURE',
       'SCIENCE & TECH', 'SPORTS', 'ENTERTAINMENT', 'POLITICS',
       'WEIRD NEWS', 'ENVIRONMENT', 'EDUCATION', 'CRIME', 'WELLNESS',
       'BUSINESS & FINANCES', 'STYLE & BEAUTY', 'FOOD & DRINK', 'MEDIA',
       'GROUPS VOICES', 'HOME & LIVING', 'WOMEN', 'TRAVEL', 'RELIGION',
       'IMPACT', 'WEDDINGS', 'MISCELLANEOUS', 'DIVORCE'], dtype=object)

In [152]:
df['category'].unique()

array(['U.S. NEWS', 'COMEDY', 'PARENTING', 'WORLD NEWS', 'CULTURE & ARTS',
       'TECH', 'SPORTS', 'ENTERTAINMENT', 'POLITICS', 'WEIRD NEWS',
       'ENVIRONMENT', 'EDUCATION', 'CRIME', 'SCIENCE', 'WELLNESS',
       'BUSINESS', 'STYLE & BEAUTY', 'FOOD & DRINK', 'MEDIA',
       'QUEER VOICES', 'HOME & LIVING', 'WOMEN', 'BLACK VOICES', 'TRAVEL',
       'MONEY', 'RELIGION', 'LATINO VOICES', 'IMPACT', 'WEDDINGS',
       'COLLEGE', 'PARENTS', 'ARTS & CULTURE', 'STYLE', 'GREEN', 'TASTE',
       'HEALTHY LIVING', 'THE WORLDPOST', 'GOOD NEWS', 'WORLDPOST',
       'FIFTY', 'ARTS', 'DIVORCE'], dtype=object)

In [153]:
df.dtypes

category          object
len_of_news       object
len_news           int64
category_merge    object
dtype: object

In [174]:
x=df['len_of_news']

In [175]:
from sklearn.preprocessing import LabelEncoder
label=LabelEncoder()
y=label.fit_transform(df['category_merge'])

In [176]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=52)

In [177]:
x_train=x_train.to_numpy()
x_test=x_test.to_numpy()

In [178]:
import numpy as np
x_train=x_train.reshape(-1,1)
x_test=x_test.reshape(-1,1)

In [183]:
encoder = OneHotEncoder(handle_unknown='ignore')
x_train= encoder.fit_transform(x_train)
x_test= encoder.transform(x_test)

In [184]:
from sklearn.tree import DecisionTreeClassifier

In [185]:
dtc= DecisionTreeClassifier()

In [ ]:
dtc.fit(x_train,y_train)

In [106]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer 
from sklearn.feature_extraction.text import TfidfVectorizer 
from sklearn.metrics.pairwise import cosine_similarity

In [143]:
def similarity(text1,text2):
    tokens1=word_tokenize(text1)
    tokens2=word_tokenize(text2)
    
    lemmatizer=WordNetLemmatizer()
    tokens1=[lemmatizer.lemmatize(token) for token in tokens1]
    tokens2=[lemmatizer.lemmatize(token) for token in tokens2]
    
    stop_words=stopwords.words('english')
    token1=[token for token in tokens1 if token not in stop_words]
    token2=[token for token in tokens2 if token not in stop_words]
    
    vectorizer=TfidfVectorizer()
    vector1=vectorizer.fit_transform(token1)
    vector2=vectorizer.transform(token2)
    
    similarity=cosine_similarity(vector1,vector2)
    
    print(similarity)

In [144]:
text1=[]
for i in df['short_description']:
    text1.append(i)

In [145]:
text2=[]
for i in df['headline']:
    text2.append(i)

In [146]:
text1[0]

'Health experts said it is too early to predict whether demand would match up with the 171 million doses of the new boosters the U.S. ordered for the fall.'

In [147]:
text2[0]

'Over 4 Million Americans Roll Up Sleeves For Omicron-Targeted COVID Boosters'

In [148]:
import textdistance
textdistance.hamming(df['headline'][1], df['short_description'][1])

154

In [149]:
similarity(df['headline'][1], df['short_description'][1])

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [154]:
textdistance.levenshtein.normalized_similarity(df['headline'][0], df['short_description'][0])

0.20779220779220775

In [158]:
for i in range(5):
    print(textdistance.levenshtein.normalized_similarity(df['headline'][i], df['short_description'][i]))
    

0.20779220779220775
0.23899371069182385
0.17391304347826086
0.16981132075471694
0.1923076923076923


In [160]:
for i in range(5):
    print(similarity(df['headline'][i], df['short_description'][i]))
    

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
None
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.

In [ ]:
import nltk
nltk.download('wordnet')